# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CoreTextDemo2hybrid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AILesson
  pod 'AFNetworking', '4.0.1'
  pod 'SDWebImage', '5.0.6'


end
